kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "limite-svc-build"
spec:
  source:
    git:
      uri: "https://github.com/csilveir/limite-svc"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "DockerImage"
      name: "172.30.1.1:5000/workshop/limite-svc:VERSION_APP"