FROM csilveir/istio-build:0.0.1

RUN mkdir /tmp/limite-svc
ADD . /tmp/limite-svc
WORKDIR /tmp/limite-svc
RUN kubectl get pods --kubeconfig=/tmp/limite-svc/.kube/config
RUN sed -i "s/VERSION_APP/$(cat gradle.properties | grep "$version" | cut -d'=' -f2)/g" istio.yml
RUN cat istio.yml
RUN istioctl kube-inject -f /tmp/limite-svc/istio.yml -n workshop --kubeconfig=/tmp/limite-svc/.kube/config | kubectl apply -f - -n workshop --kubeconfig=/tmp/limite-svc/.kube/config
RUN rm -rf /tmp/limite-svc/

