server:
  port: 8081

spring:
  application:
    name: limite-svc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: limite-svc-consumer
      group-id: limite-group
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit:  true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    enabled: true

  cache:
    expireAfterWrite: 30
    maximumSize: 1024
    allowNullValues: false

  h2:
    console:
      enabled: true
      path: /h2


app:
  topic: transaction
  returnTopic: transaction_extorno



limite:
  valorTotal: 20000